name: Run tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: ["**"]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm install --package-lock-only --force && npm ci --force

            - name: Run tests
              run: npm run test
